# Generated by Django 4.2 on 2023-04-30 04:34
import ApiApplication.models

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=2000)),
                
            ],
        ),
    ]
